import { FormEvent, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from './lib/firebase';
import { friendlyAuthError, requestPasswordReset, signIn, signOutCurrentUser, signUpOwner } from './lib/auth';
import { bootstrapOwnerWorkspace, resolveAuthorizedWorkspace, type WorkspaceAccess } from './lib/workspace';
import { AppShell } from './app/shell';
import './styles.css';

type Phase = 'loading' | 'auth' | 'onboarding' | 'inactive' | 'error' | 'ready';
type Seed = { fullName: string; mobile: string; email: string };
const blank = { fullName: '', mobile: '', email: '' };

function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) {
  return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-700">{label}</span><input {...props} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-ink outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-brand/10" /></label>;
}

function AuthCard({ onNewAccount }: { onNewAccount: (seed: Seed) => void }) {
  const [mode, setMode] = useState<'login' | 'signup' | 'reset'>('login');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ ...blank, password: '', confirmPassword: '' });
  const set = (key: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: e.target.value });
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setMessage('');
    if (!form.email.trim()) return setMessage('Enter your email address.');
    if (mode === 'reset') { setBusy(true); await requestPasswordReset(form.email); setBusy(false); return setMessage('If an account exists, reset instructions are on their way.'); }
    if (mode === 'signup' && (form.fullName.trim().length < 2 || !/^\+?[0-9\s-]{8,15}$/.test(form.mobile.trim()) || form.password.length < 8 || form.password !== form.confirmPassword)) return setMessage('Complete every field with a valid mobile number and matching 8-character password.');
    if (mode === 'login' && !form.password) return setMessage('Enter your password.');
    setBusy(true);
    try { if (mode === 'signup') { await signUpOwner(form.fullName, form.email, form.password); onNewAccount({ fullName: form.fullName.trim(), mobile: form.mobile.trim(), email: form.email.trim() }); } else await signIn(form.email, form.password); } catch (error) { setMessage(friendlyAuthError(error)); } finally { setBusy(false); }
  };
  const signup = mode === 'signup'; const reset = mode === 'reset';
  return <section className="w-full max-w-md rounded-3xl border border-slate-200/80 bg-white p-7 shadow-soft sm:p-9"><p className="text-sm font-semibold tracking-[.16em] text-brand">CREOVY HOUSE OWNER</p><h1 className="mt-4 text-3xl font-semibold tracking-tight">{reset ? 'Reset your password' : signup ? 'Create your owner account' : 'Welcome back'}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{reset ? 'We’ll securely help you get back in.' : signup ? 'Set up your portfolio in a few thoughtful steps.' : 'Sign in to your property workspace.'}</p><form className="mt-7 space-y-4" onSubmit={submit} noValidate>{signup && <><Field label="Full name" value={form.fullName} onChange={set('fullName')} autoComplete="name" placeholder="Your full name" /><Field label="Mobile number" value={form.mobile} onChange={set('mobile')} autoComplete="tel" inputMode="tel" placeholder="+91 98765 43210" /></>}<Field label="Email address" value={form.email} onChange={set('email')} autoComplete="email" inputMode="email" type="email" placeholder="you@example.com" />{!reset && <><Field label="Password" value={form.password} onChange={set('password')} autoComplete={signup ? 'new-password' : 'current-password'} type="password" placeholder="••••••••" />{signup && <Field label="Confirm password" value={form.confirmPassword} onChange={set('confirmPassword')} autoComplete="new-password" type="password" placeholder="••••••••" />}</>}{message && <p className="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600" role="status">{message}</p>}<button className="w-full rounded-xl bg-brand px-4 py-3 font-semibold text-white transition hover:bg-brand/90 disabled:cursor-wait disabled:opacity-60" disabled={busy}>{busy ? 'Please wait…' : reset ? 'Send reset link' : signup ? 'Create account' : 'Sign in'}</button></form><div className="mt-5 flex justify-between text-sm">{!reset && <button className="text-slate-500 hover:text-brand" onClick={() => setMode('reset')} type="button">Forgot password?</button>}<button className="ml-auto font-medium text-brand" onClick={() => { setMessage(''); setMode(signup || reset ? 'login' : 'signup'); }} type="button">{signup || reset ? 'Back to sign in' : 'Create account'}</button></div></section>;
}

function WorkspaceSetup({ user, seed, complete }: { user: User; seed: Seed; complete: () => void }) {
  const [form, setForm] = useState({ portfolio: '', fullName: seed.fullName || user.displayName || '', mobile: seed.mobile, email: seed.email || user.email || '' }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const set = (key: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: e.target.value });
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); if (form.portfolio.trim().length < 2 || form.fullName.trim().length < 2 || !/^\+?[0-9\s-]{8,15}$/.test(form.mobile.trim())) return setMessage('Complete your portfolio name, full name, and valid mobile number.'); setBusy(true); try { await bootstrapOwnerWorkspace({ uid: user.uid, name: form.portfolio.trim(), fullName: form.fullName.trim(), mobile: form.mobile.trim(), email: form.email.trim() }); complete(); } catch (error) { setMessage(friendlyAuthError(error)); } finally { setBusy(false); } };
  return <section className="w-full max-w-md rounded-3xl border border-slate-200/80 bg-white p-7 shadow-soft sm:p-9"><p className="text-sm font-semibold tracking-[.16em] text-brand">ONE LAST STEP</p><h1 className="mt-4 text-3xl font-semibold tracking-tight">Name your property portfolio.</h1><p className="mt-2 text-sm leading-6 text-slate-500">This creates your secure CREOVY workspace. You can invite your team later.</p><form className="mt-7 space-y-4" onSubmit={submit}><Field label="Property portfolio name" value={form.portfolio} onChange={set('portfolio')} placeholder="Raj Properties" autoFocus /><Field label="Owner full name" value={form.fullName} onChange={set('fullName')} autoComplete="name" /><Field label="Mobile number" value={form.mobile} onChange={set('mobile')} autoComplete="tel" inputMode="tel" /><Field label="Email address" value={form.email} onChange={set('email')} type="email" readOnly />{message && <p className="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600" role="status">{message}</p>}<button className="w-full rounded-xl bg-brand px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={busy}>{busy ? 'Creating secure workspace…' : 'Create workspace'}</button></form></section>;
}

function Dashboard({ workspace, user }: { workspace: WorkspaceAccess; user: User }) { return <main className="min-h-screen bg-mist p-5 sm:p-10"><section className="mx-auto max-w-6xl rounded-3xl bg-white p-7 shadow-soft sm:p-10"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold tracking-[.16em] text-brand">CREOVY HOUSE OWNER</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{workspace.name}</h1><p className="mt-2 text-slate-500">A calm, connected home for your portfolio.</p></div><button onClick={() => signOutCurrentUser()} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium hover:border-brand hover:text-brand">Log out</button></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><Info label="Owner" value={user.displayName || user.email || '—'} /><Info label="Role" value={workspace.role} /><Info label="Workspace" value="Active" /></div><div className="mt-8 rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">Your CREOVY workspace is securely connected. Property management modules will appear here next.</div></section></main>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 font-semibold capitalize text-ink">{value}</p></div>; }

function App() {
  const [phase, setPhase] = useState<Phase>('loading'); const [user, setUser] = useState<User | null>(null); const [workspace, setWorkspace] = useState<WorkspaceAccess | null>(null); const [seed, setSeed] = useState<Seed>(blank); const [refresh, setRefresh] = useState(0);
  useEffect(() => onAuthStateChanged(auth, async (current) => { setUser(current); setWorkspace(null); if (!current) return setPhase('auth'); try { const profile = await getDoc(doc(db, 'users', current.uid)); if (!profile.exists()) return setPhase('onboarding'); if (profile.data().status !== 'active') return setPhase('inactive'); const access = await resolveAuthorizedWorkspace(current.uid, profile.data().activeWorkspaceId); if (!access) return setPhase('onboarding'); setWorkspace(access); setPhase('ready'); } catch { setPhase('error'); } }), [refresh]);
  if (phase === 'ready' && user && workspace) return <AppShell workspace={workspace} owner={user.displayName || user.email || 'Owner'} onLogout={() => signOutCurrentUser()} />;
  const panel = phase === 'loading' ? <div className="w-full max-w-md rounded-3xl bg-white p-9 shadow-soft" role="status">Restoring your secure session…</div> : phase === 'onboarding' && user ? <WorkspaceSetup user={user} seed={seed} complete={() => setRefresh((value) => value + 1)} /> : phase === 'inactive' ? <div className="w-full max-w-md rounded-3xl bg-white p-9 shadow-soft"><h1 className="text-2xl font-semibold">Account unavailable</h1><p className="mt-3 text-slate-500">This CREOVY account is currently inactive. Please contact support.</p><button className="mt-6 text-brand" onClick={() => signOutCurrentUser()}>Return to sign in</button></div> : phase === 'error' ? <div className="w-full max-w-md rounded-3xl bg-white p-9 shadow-soft"><h1 className="text-2xl font-semibold">We couldn’t open your workspace</h1><p className="mt-3 text-slate-500">Please check your connection and try again.</p><button className="mt-6 text-brand" onClick={() => setRefresh((value) => value + 1)}>Try again</button></div> : <AuthCard onNewAccount={(next) => { setSeed(next); setPhase('onboarding'); }} />;
  return <main className="min-h-screen bg-mist px-5 py-10 sm:p-12"><div className="mx-auto flex min-h-[80vh] max-w-6xl items-center justify-center"><div className="grid w-full items-center gap-12 lg:grid-cols-[1fr_auto]"><div className="hidden max-w-xl lg:block"><p className="text-sm font-semibold tracking-[.18em] text-brand">PROPERTY MANAGEMENT, REFINED</p><h2 className="mt-5 text-5xl font-semibold tracking-tight text-ink">One trusted workspace for every property decision.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-slate-500">CREOVY House Owner keeps your portfolio, team, and tenant operations beautifully in sync across web and Android.</p></div>{panel}</div></div></main>;
}
export default App;
createRoot(document.getElementById('root')!).render(<App />);
