import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../data/security_deposit_financial_repository.dart';
import 'design_system.dart';
import 'receipt_screen.dart' show shapedReceiptValue, receiptDate, receiptMode;

String depositReceiptFileName(String number) => 'CREOVY-HOMS-Deposit-${number.startsWith('CRV-D-F-') ? 'Refund-' : 'Receipt-'}${number.replaceAll(RegExp(r'[^a-zA-Z0-9-]'), '-')}.pdf';

Future<Uint8List> createDepositReceiptPdf(DepositReceiptRecord receipt) async {
  final pdf = pw.Document();
  final tenant = await shapedReceiptValue(receipt.tenantName);
  final property = await shapedReceiptValue(receipt.propertyName);
  final unit = await shapedReceiptValue(receipt.unitName);
  final reference = receipt.referenceNumber.isEmpty ? null : await shapedReceiptValue(receipt.referenceNumber);
  final refund = receipt.transactionType == 'refunded';
  pw.Widget plain(String value) => pw.Text(value, textAlign: pw.TextAlign.right, style: pw.TextStyle(fontWeight: pw.FontWeight.bold));
  pw.Widget line(String label, pw.Widget value) => pw.Padding(padding: const pw.EdgeInsets.only(bottom: 13), child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, crossAxisAlignment: pw.CrossAxisAlignment.start, children: [pw.Text(label, style: const pw.TextStyle(color: PdfColors.grey700)), pw.SizedBox(width: 20), pw.Expanded(child: pw.Align(alignment: pw.Alignment.centerRight, child: value))]));
  pdf.addPage(pw.Page(pageFormat: PdfPageFormat.a4, margin: const pw.EdgeInsets.all(48), build: (_) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
    pw.Text('CREOVY HOMS', style: pw.TextStyle(color: PdfColors.deepPurple, fontSize: 15, fontWeight: pw.FontWeight.bold, letterSpacing: 2)),
    pw.SizedBox(height: 24), pw.Text(refund ? 'SECURITY DEPOSIT REFUND RECEIPT' : 'SECURITY DEPOSIT RECEIPT', style: pw.TextStyle(fontSize: 21, fontWeight: pw.FontWeight.bold)),
    pw.SizedBox(height: 6), pw.Text(receipt.receiptNumber, style: const pw.TextStyle(color: PdfColors.grey700)),
    pw.SizedBox(height: 20), pw.Divider(), pw.SizedBox(height: 22),
    line('Tenant', tenant), line('Property', property), line('Unit', unit),
    line('Agreement', plain(receipt.data['agreementId'] as String)),
    line('Transaction', plain(receipt.depositTransactionId)),
    line('Type', plain(refund ? 'Deposit refunded' : 'Deposit received')),
    line('Date', plain(receiptDate(receipt.transactionDate))),
    line('Payment mode', plain(receiptMode(receipt.paymentMode))),
    if (reference != null) line('Reference number', reference),
    pw.SizedBox(height: 6), pw.Divider(), pw.SizedBox(height: 15),
    pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [pw.Text(refund ? 'AMOUNT REFUNDED' : 'AMOUNT RECEIVED', style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 11)), pw.Text('INR ${(receipt.amountPaise / 100).toStringAsFixed(2)}', style: pw.TextStyle(color: PdfColors.deepPurple, fontSize: 22, fontWeight: pw.FontWeight.bold))]),
    pw.SizedBox(height: 14), line('Deposit agreed', plain('INR ${((receipt.data['agreedAmountPaise'] as int) / 100).toStringAsFixed(2)}')),
    line('Total received after movement', plain('INR ${((receipt.data['totalReceivedPaise'] as int) / 100).toStringAsFixed(2)}')),
    line('Held after movement', plain('INR ${((receipt.data['heldBalancePaise'] as int) / 100).toStringAsFixed(2)}')),
    pw.SizedBox(height: 12), pw.Text('Property owner security-deposit record. CREOVY did not receive or refund this money.', style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 10)),
    pw.Spacer(), pw.Divider(), pw.Text('Generated by CREOVY HOMS', style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 10)),
  ])));
  return pdf.save();
}

class DepositReceiptScreen extends StatefulWidget {
  const DepositReceiptScreen({super.key, required this.workspaceId, required this.transactionId});
  final String workspaceId, transactionId;
  @override State<DepositReceiptScreen> createState() => _DepositReceiptScreenState();
}
class _DepositReceiptScreenState extends State<DepositReceiptScreen> {
  late Future<DepositReceiptRecord?> receipt = _load();
  bool busy = false;
  Future<DepositReceiptRecord?> _load() => SecurityDepositFinancialRepository(FirebaseFirestore.instance, FirebaseAuth.instance).getDepositReceipt(widget.workspaceId, widget.transactionId);
  void _retry() => setState(() => receipt = _load());
  Future<void> _export(DepositReceiptRecord record, {required bool share}) async {
    if (busy) return;
    setState(() => busy = true);
    try {
      final bytes = await createDepositReceiptPdf(record);
      if (share) { await Printing.sharePdf(bytes: bytes, filename: depositReceiptFileName(record.receiptNumber)); }
      else { await Printing.layoutPdf(onLayout: (_) async => bytes, name: depositReceiptFileName(record.receiptNumber)); }
    } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Deposit receipt PDF could not be prepared. Please retry.'))); }
    finally { if (mounted) setState(() => busy = false); }
  }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Deposit Receipt')), body: FutureBuilder<DepositReceiptRecord?>(future: receipt, builder: (context, snapshot) {
    if (snapshot.hasError) return Center(child: Column(mainAxisSize: MainAxisSize.min, children: [const EmptyState(title: 'Receipt unavailable', body: 'Check your connection and retry.'), TextButton(onPressed: _retry, child: const Text('Retry'))]));
    if (!snapshot.hasData && snapshot.connectionState != ConnectionState.done) return const Padding(padding: EdgeInsets.all(20), child: Column(children: [Skeleton(height: 80), SizedBox(height: 12), Skeleton(height: 300)]));
    final record = snapshot.data;
    if (record == null) return const Center(child: Padding(padding: EdgeInsets.all(24), child: EmptyState(title: 'No deposit receipt', body: 'Pre-Step 7C transactions are not automatically backfilled.')));
    final refund = record.transactionType == 'refunded';
    return ListView(padding: const EdgeInsets.all(20), children: [Container(color: Colors.white, padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      const Text('CREOVY HOMS', style: TextStyle(color: CreovyColors.brand, fontWeight: FontWeight.w800, letterSpacing: 2)), const SizedBox(height: 24),
      Text(refund ? 'SECURITY DEPOSIT REFUND RECEIPT' : 'SECURITY DEPOSIT RECEIPT', style: const TextStyle(fontSize: 23, fontWeight: FontWeight.w700)),
      const SizedBox(height: 5), Text(record.receiptNumber, style: const TextStyle(color: CreovyColors.secondary)), const Divider(height: 35),
      _field('Tenant', record.tenantName), _field('Property', record.propertyName), _field('Unit', record.unitName),
      _field('Agreement', record.data['agreementId'] as String), _field('Transaction', record.depositTransactionId),
      _field('Type', refund ? 'Deposit refunded' : 'Deposit received'), _field('Date', receiptDate(record.transactionDate)),
      _field('Payment mode', receiptMode(record.paymentMode)), if (record.referenceNumber.isNotEmpty) _field('Reference', record.referenceNumber),
      const Divider(height: 32), Text(refund ? 'AMOUNT REFUNDED' : 'AMOUNT RECEIVED', style: const TextStyle(fontSize: 11, color: CreovyColors.secondary, letterSpacing: 1.4)),
      Text(formatInr(record.amountPaise), style: const TextStyle(fontSize: 28, color: CreovyColors.brand, fontWeight: FontWeight.w700)), const SizedBox(height: 12),
      _field('Deposit agreed', formatInr(record.data['agreedAmountPaise'] as int)), _field('Total received after movement', formatInr(record.data['totalReceivedPaise'] as int)), _field('Currently held after movement', formatInr(record.data['heldBalancePaise'] as int)),
      const SizedBox(height: 10), const Text('Property owner security-deposit record. CREOVY did not receive or refund this money.', style: TextStyle(fontSize: 12, color: CreovyColors.secondary)), const SizedBox(height: 50), const Divider(), const Text('Generated by CREOVY HOMS', style: TextStyle(fontSize: 12, color: CreovyColors.secondary)),
    ])), const SizedBox(height: 16), Row(children: [Expanded(child: CreovyButton(label: 'Share PDF', icon: Icons.share_outlined, loading: busy, onPressed: busy ? null : () => _export(record, share: true))), const SizedBox(width: 10), Expanded(child: CreovyButton(label: 'Export PDF', icon: Icons.picture_as_pdf_outlined, variant: CreovyButtonVariant.outline, onPressed: busy ? null : () => _export(record, share: false)))]), const SizedBox(height: 12), TextButton(onPressed: () => Navigator.pop(context), child: const Text('Back to deposit ledger'))]);
  }));
}
Widget _field(String label, String value) => Padding(padding: const EdgeInsets.only(bottom: 14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(label, style: const TextStyle(fontSize: 12, color: CreovyColors.secondary)), const SizedBox(height: 3), Text(value, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600))]));
