import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

import '../data/account_resolver.dart';
import '../data/property_repository.dart';
import '../data/tenant_repository.dart';
import 'design_system.dart';
import 'property_bills_screen.dart';
import 'agreement_screens.dart';

class PropertiesScreen extends StatelessWidget { const PropertiesScreen({super.key, required this.account}); final AccountContext account; @override Widget build(BuildContext context) => StreamBuilder<List<PropertyRecord>>(stream: PropertyRepository(FirebaseFirestore.instance).watchProperties(account.workspaceId), builder: (context, snapshot) { if (snapshot.hasError) return const Center(child: EmptyState(title: 'Unable to load properties', body: 'Please try again shortly.')); if (!snapshot.hasData) return ListView(padding: const EdgeInsets.all(20), children: const [Skeleton(height: 74), SizedBox(height: 12), Skeleton(height: 74)]); final properties = snapshot.data!; return Scaffold(floatingActionButton: FloatingActionButton.extended(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => PropertyEditor(account: account))), label: const Text('Add Property'), icon: const Icon(Icons.add)), body: properties.isEmpty ? Center(child: Padding(padding: const EdgeInsets.all(24), child: EmptyState(title: 'Your portfolio is ready for its first property', body: 'Add your first property to start managing units, tenants and rent.'))) : ListView(padding: const EdgeInsets.fromLTRB(20, 12, 20, 90), children: [TextField(decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'Search properties')), const SizedBox(height: 18), ...properties.map((property) => Padding(padding: const EdgeInsets.only(bottom: 12), child: _PropertyCard(account: account, property: property)))])); }); }
}

class _PropertyCard extends StatelessWidget { const _PropertyCard({required this.account, required this.property}); final AccountContext account; final PropertyRecord property; @override Widget build(BuildContext context) => SurfaceCard(child: InkWell(onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => PropertyDetail(account: account, property: property))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text(property.data['name'] as String? ?? 'Property', style: const TextStyle(fontSize: 17, fontWeight: FontWeight.w700))), StatusChip(label: property.data['status'] == 'inactive' ? 'Inactive' : 'Active')]), const SizedBox(height: 5), Text('${property.data['code'] ?? '—'} · ${_label(property.data['type'] as String? ?? 'other')}', style: const TextStyle(fontSize: 13, color: CreovyColors.secondary)), const SizedBox(height: 10), Text('${property.data['locality'] ?? property.data['city'] ?? ''}', style: const TextStyle(color: CreovyColors.secondary)), const SizedBox(height: 14), StreamBuilder<List<UnitRecord>>(stream: PropertyRepository(FirebaseFirestore.instance).watchUnits(account.workspaceId, property.id), builder: (context, units) { if (!units.hasData) return const Skeleton(height: 18, width: 150); final active = units.data!.where((item) => item.data['status'] != 'inactive').toList(); final occupied = active.where((item) => item.data['status'] == 'occupied').length; final rent = active.fold<int>(0, (sum, item) => sum + ((item.data['monthlyRentPaise'] as num?)?.toInt() ?? 0)); return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text('${active.length} Units · $occupied Occupied', style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600)), Text(formatInr(rent), style: const TextStyle(fontWeight: FontWeight.w700))]); })]))); }
}

class PropertyEditor extends StatefulWidget { const PropertyEditor({super.key, required this.account}); final AccountContext account; @override State<PropertyEditor> createState() => _PropertyEditorState(); }
class _PropertyEditorState extends State<PropertyEditor> { final _form = GlobalKey<FormState>(); final _name = TextEditingController(), _code = TextEditingController(), _address = TextEditingController(), _locality = TextEditingController(), _city = TextEditingController(), _state = TextEditingController(), _pin = TextEditingController(), _owner = TextEditingController(), _tax = TextEditingController(), _water = TextEditingController(); String _type = 'independent_house'; bool _firstUnit = true, _busy = false; int _step = 0;
  @override void dispose() { for (final c in [_name,_code,_address,_locality,_city,_state,_pin,_owner,_tax,_water]) { c.dispose(); } super.dispose(); }
  Future<void> _save() async { if (!(_form.currentState?.validate() ?? false)) return; setState(() => _busy = true); try { await PropertyRepository(FirebaseFirestore.instance).createProperty(workspaceId: widget.account.workspaceId, property: {'name': _name.text.trim(), 'type': _type, 'code': _code.text.trim(), 'addressLine1': _address.text.trim(), 'addressLine2': '', 'locality': _locality.text.trim(), 'city': _city.text.trim(), 'district': '', 'state': _state.text.trim(), 'pinCode': _pin.text.trim(), 'country': 'India', 'ownerName': _owner.text.trim().isEmpty ? widget.account.ownerName : _owner.text.trim(), 'propertyTaxAssessmentNumber': _tax.text.trim(), 'waterConnectionNumber': _water.text.trim(), 'notes': ''}, initialUnits: _firstUnit && _type == 'independent_house' ? [{'name': 'House 01', 'type': 'house', 'floor': '', 'bhk': '', 'monthlyRentPaise': 0, 'expectedSecurityDepositPaise': 0, 'ebServiceNumber': '', 'notes': ''}] : []); if (mounted) Navigator.pop(context); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString()))); } finally { if (mounted) setState(() => _busy = false); } }
  @override Widget build(BuildContext context) { final headings = ['Property Details', 'Address', 'Government References', 'Units', 'Review']; return Scaffold(appBar: AppBar(title: Text(headings[_step])), body: Form(key: _form, child: ListView(padding: const EdgeInsets.all(20), children: [_step == 0 ? Column(children: [_field(_name, 'Property name *'), const SizedBox(height: 14), DropdownButtonFormField(value: _type, items: const [DropdownMenuItem(value: 'independent_house', child: Text('Independent House')), DropdownMenuItem(value: 'apartment_building', child: Text('Apartment / Residential Building')), DropdownMenuItem(value: 'commercial_building', child: Text('Commercial Building')), DropdownMenuItem(value: 'mixed_use', child: Text('Mixed Use')), DropdownMenuItem(value: 'other', child: Text('Other'))], onChanged: (value) => setState(() => _type = value!), decoration: const InputDecoration(labelText: 'Property type')), const SizedBox(height: 14), _field(_code, 'Property code', required: false), const SizedBox(height: 14), _field(_owner, 'Owner name', required: false)]) : _step == 1 ? Column(children: [_field(_address, 'Address line 1 *'), const SizedBox(height: 14), _field(_locality, 'Area / locality', required: false), const SizedBox(height: 14), _field(_city, 'City *'), const SizedBox(height: 14), _field(_state, 'State *'), const SizedBox(height: 14), _field(_pin, 'PIN code *')]) : _step == 2 ? Column(children: [_field(_tax, 'Property tax assessment number', required: false), const SizedBox(height: 14), _field(_water, 'Water connection number', required: false)]) : _step == 3 ? CheckboxListTile(value: _firstUnit, onChanged: (value) => setState(() => _firstUnit = value ?? false), title: const Text('Create first editable unit “House 01”'), subtitle: const Text('You can add and edit unit details next.')) : SurfaceCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(_name.text, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w700)), const SizedBox(height: 8), Text(_type), const SizedBox(height: 8), Text('${_address.text}, ${_city.text}'), const SizedBox(height: 16), Text(_firstUnit ? 'House 01 will be created as vacant.' : 'Units can be added after creation.')]))]), const SizedBox(height: 24), Row(children: [if (_step > 0) Expanded(child: CreovyButton(label: 'Back', variant: CreovyButtonVariant.outline, onPressed: () => setState(() => _step--))), if (_step > 0) const SizedBox(width: 12), Expanded(child: CreovyButton(label: _step == 4 ? 'Create Property' : 'Continue', loading: _busy, onPressed: _step == 4 ? _save : () { if (_step < 4) setState(() => _step++); }))])]))); }
  Widget _field(TextEditingController controller, String label, {bool required = true}) => TextFormField(controller: controller, validator: required ? (v) => v == null || v.trim().isEmpty ? 'Enter $label' : null : null, decoration: InputDecoration(labelText: label));
}

class PropertyDetail extends StatelessWidget { const PropertyDetail({super.key, required this.account, required this.property}); final AccountContext account; final PropertyRecord property; @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(property.data['name'] as String? ?? 'Property'), actions: [IconButton(onPressed: () => PropertyRepository(FirebaseFirestore.instance).archiveProperty(property.id), icon: const Icon(Icons.archive_outlined))]), body: StreamBuilder<List<UnitRecord>>(stream: PropertyRepository(FirebaseFirestore.instance).watchUnits(account.workspaceId, property.id), builder: (context, snapshot) { final units = snapshot.data ?? []; final active = units.where((item) => item.data['status'] != 'inactive').toList(); return ListView(padding: const EdgeInsets.all(20), children: [Text('${property.data['code']} · ${_label(property.data['type'] as String? ?? 'other')}', style: const TextStyle(color: CreovyColors.secondary)), const SizedBox(height: 20), Row(children: [_summary('Units', active.length.toString()), _summary('Occupied', active.where((item) => item.data['status'] == 'occupied').length.toString()), _summary('Vacant', active.where((item) => item.data['status'] == 'vacant').length.toString())]), const SizedBox(height: 18), CreovyButton(label: 'Bills & Taxes', icon: Icons.receipt_long_outlined, variant: CreovyButtonVariant.outline, onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => PropertyBillsScreen(account: account, initialPropertyId: property.id)))), const SizedBox(height: 24), const Text('Units', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 10), if (!snapshot.hasData) const Skeleton(height: 64) else if (units.isEmpty) const EmptyState(title: 'No units yet', body: 'Add a rentable unit to this property.') else ...units.map((unit) => Padding(padding: const EdgeInsets.only(bottom: 10), child: _UnitContextRow(account: account, unit: unit))), const SizedBox(height: 20), const Text('Government References', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 10), SurfaceCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Property Tax: ${property.data['propertyTaxAssessmentNumber'] ?? 'Not added'}'), const SizedBox(height: 10), Text('Water Connection: ${property.data['waterConnectionNumber'] ?? 'Not added'}')]))]); })); Widget _summary(String label, String value) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 8), child: SurfaceCard(padding: const EdgeInsets.all(10), child: Column(children: [Text(label, style: const TextStyle(fontSize: 11, color: CreovyColors.secondary)), const SizedBox(height: 5), Text(value, style: const TextStyle(fontWeight: FontWeight.w700))])))); }
class _UnitContextRow extends StatelessWidget { const _UnitContextRow({required this.account, required this.unit}); final AccountContext account; final UnitRecord unit; @override Widget build(BuildContext context) => StreamBuilder<List<AgreementRecord>>(stream: TenantRepository(FirebaseFirestore.instance).watchAgreements(account.workspaceId), builder: (context, agreements) => StreamBuilder<List<TenantRecord>>(stream: TenantRepository(FirebaseFirestore.instance).watchTenants(account.workspaceId), builder: (context, tenants) { final active = (agreements.data ?? []).where((item) => item.data['unitId'] == unit.id && item.data['status'] == 'active').toList(); final upcoming = (agreements.data ?? []).where((item) => item.data['unitId'] == unit.id && item.data['status'] == 'upcoming').toList(); final agreement = active.isEmpty ? null : active.first; final tenant = agreement == null ? null : (tenants.data ?? []).where((item) => item.id == agreement.data['tenantId']).cast<TenantRecord?>().firstOrNull; return SurfaceCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [ListTile(contentPadding: EdgeInsets.zero, title: Text(unit.data['name'] as String? ?? 'Unit'), subtitle: Text('${_label(unit.data['type'] as String? ?? 'other')} · ${unit.data['floor'] ?? 'No floor'} · ${formatInr((unit.data['monthlyRentPaise'] as num?)?.toInt())}'), trailing: StatusChip(label: _label(unit.data['status'] as String? ?? 'vacant'))), if (agreement != null && tenant != null) Row(children: [Expanded(child: Text('Current Tenant: ${tenant.data['fullName']}', style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600))), TextButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => TenantDetailScreen(account: account, tenant: tenant))), child: const Text('View Tenant')), TextButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => AgreementDetailScreen(account: account, agreement: agreement))), child: const Text('View Agreement'))]) else if (upcoming.isNotEmpty) const Text('Upcoming Agreement', style: TextStyle(fontSize: 13, color: CreovyColors.secondary))])); })); }
String _label(String value) => value.replaceAll('_', ' ').split(' ').map((item) => item.isEmpty ? item : '${item[0].toUpperCase()}${item.substring(1)}').join(' ');
