import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../data/financial_record_repository.dart';
import 'design_system.dart';

String receiptFileName(String number) => 'CREOVY-HOMS-Receipt-${number.replaceAll(RegExp(r'[^a-zA-Z0-9-]'), '-')}.pdf';
String receiptDate(Timestamp value) { final india = value.toDate().toUtc().add(const Duration(hours: 5, minutes: 30)); return '${india.day.toString().padLeft(2, '0')}/${india.month.toString().padLeft(2, '0')}/${india.year}'; }
String receiptMode(String value) => switch (value) { 'cash' => 'Cash', 'upi' => 'UPI', 'bank_transfer' => 'Bank Transfer', 'cheque' => 'Cheque', _ => 'Other' };
String receiptPeriod(String value) => RegExp(r'^\d{4}-\d{2}$').hasMatch(value) ? '${value.substring(5)}/${value.substring(0, 4)}' : value;

// package:pdf does not shape Tamil vowel signs and conjuncts. Flutter's text
// engine does; rasterize only variable receipt values with the bundled font.
Future<pw.Widget> shapedReceiptValue(String value, {double width = 300, TextAlign alignment = TextAlign.right, double fontSize = 11}) async {
  const scale = 3.0;
  final painter = TextPainter(
    text: TextSpan(text: value, style: TextStyle(fontFamily: 'CreovyReceiptTamil', fontSize: fontSize, fontWeight: FontWeight.w600, color: Colors.black)),
    textDirection: ui.TextDirection.ltr,
    textAlign: alignment,
  )..layout(maxWidth: width);
  final recorder = ui.PictureRecorder();
  final canvas = ui.Canvas(recorder)..scale(scale);
  painter.paint(canvas, Offset.zero);
  final image = await recorder.endRecording().toImage((painter.width * scale).ceil(), (painter.height * scale).ceil());
  try {
    final pixels = await image.toByteData(format: ui.ImageByteFormat.png);
    if (pixels == null) throw StateError('Receipt text could not be rendered.');
    return pw.Image(
      pw.MemoryImage(pixels.buffer.asUint8List(pixels.offsetInBytes, pixels.lengthInBytes)),
      width: painter.width,
      height: painter.height,
    );
  } finally {
    image.dispose();
    painter.dispose();
  }
}

Future<Uint8List> createReceiptPdf(RentReceiptRecord receipt) async {
  final pdf = pw.Document();
  final tenant = await shapedReceiptValue(receipt.tenantName);
  final property = await shapedReceiptValue(receipt.propertyName);
  final unit = await shapedReceiptValue(receipt.unitName);
  final reference = receipt.referenceNumber.isEmpty ? null : await shapedReceiptValue(receipt.referenceNumber);
  pw.Widget plain(String value) => pw.Text(value, textAlign: pw.TextAlign.right, style: pw.TextStyle(fontWeight: pw.FontWeight.bold));
  pw.Widget line(String title, pw.Widget value) => pw.Padding(padding: const pw.EdgeInsets.only(bottom: 14), child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, crossAxisAlignment: pw.CrossAxisAlignment.start, children: [pw.Text(title, style: const pw.TextStyle(color: PdfColors.grey700)), pw.SizedBox(width: 22), pw.Expanded(child: pw.Align(alignment: pw.Alignment.centerRight, child: value))]));
  pdf.addPage(pw.Page(pageFormat: PdfPageFormat.a4, margin: const pw.EdgeInsets.all(48), build: (_) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
    pw.Text('CREOVY HOMS', style: pw.TextStyle(color: PdfColors.deepPurple, fontSize: 15, fontWeight: pw.FontWeight.bold, letterSpacing: 2)),
    pw.SizedBox(height: 26), pw.Text('RENT RECEIPT', style: pw.TextStyle(fontSize: 25, fontWeight: pw.FontWeight.bold)),
    pw.SizedBox(height: 6), pw.Text(receipt.receiptNumber, style: const pw.TextStyle(color: PdfColors.grey700)),
    pw.SizedBox(height: 22), pw.Divider(), pw.SizedBox(height: 24),
    line('Tenant', tenant), line('Property', property), line('Unit', unit),
    pw.SizedBox(height: 14), line('Rent period', plain(receiptPeriod(receipt.periodKey))), line('Payment date', plain(receiptDate(receipt.paymentDate))), line('Payment mode', plain(receiptMode(receipt.paymentMode))),
    if (reference != null) line('Reference number', reference),
    pw.SizedBox(height: 8), pw.Divider(), pw.SizedBox(height: 18),
    pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [pw.Text('AMOUNT RECEIVED', style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 11)), pw.Text('INR ${(receipt.amountPaise / 100).toStringAsFixed(2)}', style: pw.TextStyle(color: PdfColors.deepPurple, fontSize: 22, fontWeight: pw.FontWeight.bold))]),
    pw.SizedBox(height: 12), pw.Text('Property owner rent collection record', style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 10)),
    pw.Spacer(), pw.Divider(), pw.Text('Generated by CREOVY HOMS', style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 10)),
  ])));
  return pdf.save();
}

class ReceiptScreen extends StatefulWidget {
  const ReceiptScreen({super.key, required this.workspaceId, required this.paymentId});
  final String workspaceId, paymentId;
  @override State<ReceiptScreen> createState() => _ReceiptScreenState();
}
class _ReceiptScreenState extends State<ReceiptScreen> {
  late Future<RentReceiptRecord?> receipt = _load();
  bool busy = false;
  Future<RentReceiptRecord?> _load() => FinancialRecordRepository(FirebaseFirestore.instance, FirebaseAuth.instance).getReceiptByPayment(widget.workspaceId, widget.paymentId);
  void _retry() => setState(() => receipt = _load());
  Future<void> _export(RentReceiptRecord record, {required bool share}) async {
    if (busy) return;
    setState(() => busy = true);
    try {
      final bytes = await createReceiptPdf(record);
      if (share) { await Printing.sharePdf(bytes: bytes, filename: receiptFileName(record.receiptNumber)); }
      else { await Printing.layoutPdf(onLayout: (_) async => bytes, name: receiptFileName(record.receiptNumber)); }
    } catch (_) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Receipt PDF could not be prepared. Please retry.')));
    } finally { if (mounted) setState(() => busy = false); }
  }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Rent Receipt')), body: FutureBuilder<RentReceiptRecord?>(future: receipt, builder: (context, snapshot) {
    if (snapshot.hasError) return Center(child: Padding(padding: const EdgeInsets.all(24), child: Column(mainAxisSize: MainAxisSize.min, children: [const EmptyState(title: 'Receipt unavailable', body: 'Please check your connection and try again.'), TextButton(onPressed: _retry, child: const Text('Retry'))])));
    if (!snapshot.hasData && snapshot.connectionState != ConnectionState.done) return const Padding(padding: EdgeInsets.all(20), child: Column(children: [Skeleton(height: 70), SizedBox(height: 15), Skeleton(height: 310)]));
    final record = snapshot.data;
    if (record == null) return const Center(child: Padding(padding: EdgeInsets.all(24), child: EmptyState(title: 'No receipt for this payment', body: 'Payments recorded before receipts were introduced may not have one.')));
    return ListView(padding: const EdgeInsets.all(20), children: [
      Container(color: Colors.white, padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const Text('CREOVY HOMS', style: TextStyle(color: CreovyColors.brand, fontWeight: FontWeight.w800, letterSpacing: 2)),
        const SizedBox(height: 28), const Text('RENT RECEIPT', style: TextStyle(fontSize: 26, fontWeight: FontWeight.w700, color: CreovyColors.ink)),
        const SizedBox(height: 5), Text(record.receiptNumber, style: const TextStyle(color: CreovyColors.secondary)),
        const Divider(height: 42), _receiptField('Tenant', record.tenantName), _receiptField('Property', record.propertyName), _receiptField('Unit', record.unitName),
        const Divider(height: 36), _receiptField('Rent period', receiptPeriod(record.periodKey)), _receiptField('Payment date', receiptDate(record.paymentDate)), _receiptField('Payment mode', receiptMode(record.paymentMode)),
        if (record.referenceNumber.isNotEmpty) _receiptField('Reference number', record.referenceNumber),
        const Divider(height: 36), const Text('AMOUNT RECEIVED', style: TextStyle(fontSize: 11, color: CreovyColors.secondary, letterSpacing: 1.5, fontWeight: FontWeight.w700)),
        const SizedBox(height: 5), Text(formatInr(record.amountPaise), style: const TextStyle(fontSize: 28, color: CreovyColors.brand, fontWeight: FontWeight.w700)),
        const SizedBox(height: 10), const Text('Property owner rent collection record. CREOVY did not receive this payment.', style: TextStyle(fontSize: 12, color: CreovyColors.secondary)),
        const SizedBox(height: 65), const Divider(), const Text('Generated by CREOVY HOMS', style: TextStyle(fontSize: 12, color: CreovyColors.secondary)),
      ])), const SizedBox(height: 18), Row(children: [Expanded(child: CreovyButton(label: 'Share Receipt', icon: Icons.share_outlined, loading: busy, onPressed: busy ? null : () => _export(record, share: true))), const SizedBox(width: 10), Expanded(child: CreovyButton(label: 'Save / Export PDF', icon: Icons.picture_as_pdf_outlined, variant: CreovyButtonVariant.outline, onPressed: busy ? null : () => _export(record, share: false)))]),
    ]);
  }));
}
Widget _receiptField(String label, String value) => Padding(padding: const EdgeInsets.only(bottom: 17), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(label, style: const TextStyle(fontSize: 12, color: CreovyColors.secondary)), const SizedBox(height: 3), Text(value, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600, color: CreovyColors.ink))]));

class ReceiptsScreen extends StatefulWidget {
  const ReceiptsScreen({super.key, required this.workspaceId});
  final String workspaceId;
  @override State<ReceiptsScreen> createState() => _ReceiptsScreenState();
}
class _ReceiptsScreenState extends State<ReceiptsScreen> {
  late Future<List<RentReceiptRecord>> receipts = _load();
  Future<List<RentReceiptRecord>> _load() => FinancialRecordRepository(FirebaseFirestore.instance, FirebaseAuth.instance).listWorkspaceReceipts(widget.workspaceId);
  void _retry() => setState(() => receipts = _load());
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Receipts')), body: FutureBuilder<List<RentReceiptRecord>>(future: receipts, builder: (context, snapshot) {
    if (snapshot.hasError) return Center(child: Column(mainAxisSize: MainAxisSize.min, children: [const EmptyState(title: 'Receipts unavailable', body: 'Please check your connection and try again.'), TextButton(onPressed: _retry, child: const Text('Retry'))]));
    if (!snapshot.hasData) return const Padding(padding: EdgeInsets.all(20), child: Column(children: [Skeleton(height: 90), SizedBox(height: 12), Skeleton(height: 90)]));
    if (snapshot.data!.isEmpty) return const Center(child: Padding(padding: EdgeInsets.all(24), child: EmptyState(title: 'No receipts yet', body: 'Receipts appear when rent payments are recorded.')));
    return ListView(padding: const EdgeInsets.all(20), children: snapshot.data!.map((item) => Padding(padding: const EdgeInsets.only(bottom: 11), child: SurfaceCard(child: ListTile(contentPadding: EdgeInsets.zero, title: Text(item.tenantName, style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Text('${item.propertyName} · ${item.unitName}\n${item.receiptNumber} · ${receiptDate(item.paymentDate)}'), isThreeLine: true, trailing: Text(formatInr(item.amountPaise), style: const TextStyle(fontWeight: FontWeight.w700)), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => ReceiptScreen(workspaceId: widget.workspaceId, paymentId: item.paymentId)))))).toList());
  }));
}
