import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../data/account_resolver.dart';
import '../data/tenant_repository.dart';
import 'design_system.dart';
import 'agreement_screens.dart';

class TenantsScreen extends StatelessWidget { const TenantsScreen({super.key, required this.account}); final AccountContext account; @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Tenants')), floatingActionButton: FloatingActionButton.extended(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => TenantEditor(account: account))), label: const Text('Add Tenant'), icon: const Icon(Icons.add)), body: StreamBuilder<List<TenantRecord>>(stream: TenantRepository(FirebaseFirestore.instance).watchTenants(account.workspaceId), builder: (context, snapshot) { if (!snapshot.hasData) return const Padding(padding: EdgeInsets.all(20), child: Skeleton(height: 72)); final tenants = snapshot.data!; if (tenants.isEmpty) return const Center(child: Padding(padding: EdgeInsets.all(24), child: EmptyState(title: 'No tenants yet', body: 'Add a tenant now, then create a rental agreement when they move in.'))); return ListView(padding: const EdgeInsets.all(20), children: [TextField(decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'Search tenants')), const SizedBox(height: 16), ...tenants.map((tenant) => Padding(padding: const EdgeInsets.only(bottom: 10), child: SurfaceCard(child: ListTile(onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => TenantDetailScreen(account: account, tenant: tenant))), contentPadding: EdgeInsets.zero, title: Text(tenant.data['fullName'] as String? ?? 'Tenant'), subtitle: Text(tenant.data['mobile'] as String? ?? ''), trailing: StatusChip(label: tenant.data['status'] == 'active' ? 'Active' : 'Inactive')))))]); })); }
}
class TenantEditor extends StatefulWidget { const TenantEditor({super.key, required this.account}); final AccountContext account; @override State<TenantEditor> createState() => _TenantEditorState(); }
class _TenantEditorState extends State<TenantEditor> { final _form = GlobalKey<FormState>(); final _name = TextEditingController(), _mobile = TextEditingController(), _email = TextEditingController(), _address = TextEditingController(), _city = TextEditingController(), _idType = TextEditingController(), _idNumber = TextEditingController(), _emergency = TextEditingController(); int _step = 0; bool _busy = false; @override void dispose() { for (final c in [_name,_mobile,_email,_address,_city,_idType,_idNumber,_emergency]) { c.dispose(); } super.dispose(); } Future<void> _save() async { if (!(_form.currentState?.validate() ?? false)) return; setState(() => _busy = true); await TenantRepository(FirebaseFirestore.instance).createTenant(widget.account.workspaceId, {'fullName': _name.text.trim(), 'mobile': _mobile.text.trim(), 'email': _email.text.trim(), 'addressLine1': _address.text.trim(), 'city': _city.text.trim(), 'idType': _idType.text.trim(), 'idNumber': _idNumber.text.trim(), 'emergencyContactName': _emergency.text.trim()}); if (mounted) Navigator.pop(context); } @override Widget build(BuildContext context) { final title = ['Personal Details', 'Permanent Address', 'Identity', 'Emergency Contact', 'Review'][_step]; return Scaffold(appBar: AppBar(title: Text(title)), body: Form(key: _form, child: ListView(padding: const EdgeInsets.all(20), children: [_step == 0 ? Column(children: [_field(_name, 'Full name *'), const SizedBox(height: 14), _field(_mobile, 'Mobile number *'), const SizedBox(height: 14), _field(_email, 'Email')]) : _step == 1 ? Column(children: [_field(_address, 'Address line 1'), const SizedBox(height: 14), _field(_city, 'City')]) : _step == 2 ? Column(children: [_field(_idType, 'ID type'), const SizedBox(height: 14), _field(_idNumber, 'ID number')]) : _step == 3 ? _field(_emergency, 'Emergency contact name') : const SurfaceCard(child: Text('Tenant can be created without an agreement. Create one when they are ready to move in.')), const SizedBox(height: 26), Row(children: [if (_step > 0) Expanded(child: CreovyButton(label: 'Back', variant: CreovyButtonVariant.outline, onPressed: () => setState(() => _step--))), if (_step > 0) const SizedBox(width: 10), Expanded(child: CreovyButton(label: _step == 4 ? 'Create Tenant' : 'Continue', loading: _busy, onPressed: _step == 4 ? _save : () => setState(() => _step++)))])]))); } Widget _field(TextEditingController controller, String label) => TextFormField(controller: controller, validator: label.contains('*') ? (v) => v == null || v.trim().isEmpty ? 'Enter $label' : null : null, decoration: InputDecoration(labelText: label)); }
