import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode } from 'react';

export function Button({ children, variant = 'primary', loading, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive'; loading?: boolean }) {
  const styles = { primary: 'bg-brand text-white hover:bg-brand/90', secondary: 'bg-ink text-white hover:bg-ink/90', outline: 'border border-slate-200 bg-white text-ink hover:border-brand hover:text-brand', ghost: 'text-slate-600 hover:bg-slate-100', destructive: 'bg-danger text-white hover:bg-danger/90' };
  return <button {...props} disabled={loading || props.disabled} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition focus-visible:outline-brand disabled:cursor-wait disabled:opacity-60 ${styles[variant]} ${className}`}>{loading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />}{children}</button>;
}

export function StatusChip({ status }: { status: 'Paid' | 'Partial' | 'Pending' | 'Overdue' | 'Occupied' | 'Vacant' | 'Active' | 'Inactive' }) {
  const colors = { Paid: 'bg-emerald-50 text-emerald-800', Partial: 'bg-blue-50 text-blue-800', Pending: 'bg-amber-50 text-amber-800', Overdue: 'bg-red-50 text-red-800', Occupied: 'bg-violet-50 text-violet-800', Vacant: 'bg-slate-100 text-slate-700', Active: 'bg-emerald-50 text-emerald-800', Inactive: 'bg-slate-100 text-slate-700' };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${colors[status]}`}>{status}</span>;
}

export function TextInput({ label, error, success, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string; success?: string }) { return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-700">{label}</span><input {...props} className={`w-full rounded-xl border bg-white px-4 py-3 text-ink outline-none transition focus:ring-4 ${error ? 'border-red-400 focus:ring-red-100' : success ? 'border-emerald-500 focus:ring-emerald-100' : 'border-slate-200 focus:border-brand focus:ring-brand/10'}`} />{(error || success) && <span className={`mt-1.5 block text-xs ${error ? 'text-red-700' : 'text-emerald-700'}`}>{error || success}</span>}</label>; }
export function ToastNotice({ message, tone = 'info' }: { message: string; tone?: 'info' | 'success' | 'danger' }) { const colors = { info: 'border-blue-200 bg-blue-50 text-blue-900', success: 'border-emerald-200 bg-emerald-50 text-emerald-900', danger: 'border-red-200 bg-red-50 text-red-900' }; return <div role="status" className={`rounded-xl border px-4 py-3 text-sm ${colors[tone]}`}>{message}</div>; }
export function ConfirmationDialog({ title, body, confirmLabel, onConfirm, onCancel }: { title: string; body: string; confirmLabel: string; onConfirm: () => void; onCancel: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/25 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-soft"><h2 className="font-semibold text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p><div className="mt-6 flex justify-end gap-3"><Button variant="ghost" onClick={onCancel}>Cancel</Button><Button onClick={onConfirm}>{confirmLabel}</Button></div></section></div>; }

export function Skeleton({ className = '' }: { className?: string }) { return <div aria-label="Loading" className={`animate-pulse rounded-lg bg-slate-100 ${className}`} />; }
export function EmptyState({ title, body, action }: { title: string; body: string; action?: ReactNode }) { return <div className="flex min-h-44 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 px-6 text-center"><p className="font-semibold text-ink">{title}</p><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">{body}</p>{action && <div className="mt-4">{action}</div>}</div>; }
export function SectionCard({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <section className="rounded-2xl border border-slate-200/80 bg-white p-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold text-ink">{title}</h2>{action}</div>{children}</section>; }
