import { useEffect, useState } from 'react';
import { EmptyState, SectionCard, Skeleton } from '../../design/components';
import { formatDate, formatINR } from '../../design/tokens';
import { listWorkspaceReceipts, type RentReceipt } from './financial-record-repository';

export function ReceiptsPage({ workspaceId, viewReceipt }: { workspaceId: string; viewReceipt: (paymentId: string) => void }) {
  const [items, setItems] = useState<RentReceipt[] | null>(null);
  const [error, setError] = useState(false);
  const [revision, setRevision] = useState(0);
  const [search, setSearch] = useState('');
  useEffect(() => { let active = true; setItems(null); setError(false); listWorkspaceReceipts(workspaceId).then(value => { if (active) setItems(value); }).catch(() => { if (active) setError(true); }); return () => { active = false; }; }, [workspaceId, revision]);
  const filtered = (items ?? []).filter(item => `${item.receiptNumber} ${item.tenantName} ${item.propertyName} ${item.unitName}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><div><p className="text-sm text-slate-500">Rent collection records</p><h1 className="mt-1 text-3xl font-semibold">Receipts</h1><p className="mt-2 text-sm text-slate-500">Read-only receipts generated with recorded payments.</p></div><input value={search} onChange={event => setSearch(event.target.value)} aria-label="Search receipts" placeholder="Search tenant, property or receipt number" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" />{error ? <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">Receipts could not be loaded. <button onClick={() => setRevision(value => value + 1)} className="font-semibold underline">Retry</button></div> : items === null ? <Skeleton className="h-48" /> : filtered.length === 0 ? <EmptyState title="No receipts in this view" body="Receipts appear when new rent payments are recorded." /> : <SectionCard title={`${filtered.length} Receipts`}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr>{['Receipt', 'Date', 'Tenant', 'Property / Unit', 'Amount', ''].map(label => <th key={label} className="pb-3 pr-4">{label}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="py-4 pr-4 font-semibold">{item.receiptNumber}</td><td className="pr-4">{formatDate(item.paymentDate.toDate())}</td><td className="pr-4">{item.tenantName}</td><td className="pr-4">{item.propertyName}<br /><span className="text-xs text-slate-500">{item.unitName}</span></td><td className="pr-4 font-semibold tabular-nums">{formatINR(item.amountPaise)}</td><td><button className="font-semibold text-brand" onClick={() => viewReceipt(item.paymentId)}>View Receipt</button></td></tr>)}</tbody></table></div></SectionCard>}</div>;
}
