import { collection, doc, getDocs, onSnapshot, query, runTransaction, serverTimestamp, updateDoc, where, type Unsubscribe } from 'firebase/firestore';
import { db } from '../../lib/firebase';

export type TenantStatus = 'active' | 'former' | 'inactive';
export type AgreementStatus = 'draft' | 'upcoming' | 'active' | 'ended' | 'cancelled';
export type Tenant = { id: string; workspaceId: string; fullName: string; mobile: string; alternateMobile?: string; email?: string; dateOfBirth?: string; gender?: string; addressLine1?: string; addressLine2?: string; locality?: string; city?: string; district?: string; state?: string; pinCode?: string; idType?: string; idNumber?: string; emergencyContactName?: string; emergencyContactRelationship?: string; emergencyContactMobile?: string; occupation?: string; employer?: string; notes?: string; status: TenantStatus; };
export type Agreement = { id: string; workspaceId: string; tenantId: string; propertyId: string; unitId: string; startDate: string; endDate?: string; monthlyRentPaise: number; securityDepositAgreedPaise: number; rentDueDay: number; noticePeriodDays?: number; escalationNotes?: string; notes?: string; status: AgreementStatus; };
const map = <T>(item: { id: string; data: () => unknown }) => ({ id: item.id, ...(item.data() as Omit<T, 'id'>) }) as T;
export function listenTenants(workspaceId: string, next: (items: Tenant[]) => void, fail: (error: Error) => void): Unsubscribe { return onSnapshot(query(collection(db, 'tenants'), where('workspaceId', '==', workspaceId)), snapshot => next(snapshot.docs.map(item => map<Tenant>(item))), fail); }
export function listenAgreements(workspaceId: string, next: (items: Agreement[]) => void, fail: (error: Error) => void): Unsubscribe { return onSnapshot(query(collection(db, 'rentalAgreements'), where('workspaceId', '==', workspaceId)), snapshot => next(snapshot.docs.map(item => map<Agreement>(item))), fail); }
export async function createTenant(workspaceId: string, data: Omit<Tenant, 'id' | 'workspaceId' | 'status'>) { const reference = doc(collection(db, 'tenants')); await runTransaction(db, transaction => { transaction.set(reference, { ...data, workspaceId, status: 'inactive', createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); return Promise.resolve(); }); return reference.id; }
export async function createAgreement(workspaceId: string, data: Omit<Agreement, 'id' | 'workspaceId' | 'status'>) { if (data.rentDueDay < 1 || data.rentDueDay > 28) throw new Error('Rent due day must be between 1 and 28.'); const reference = doc(collection(db, 'rentalAgreements')); await runTransaction(db, transaction => { transaction.set(reference, { ...data, workspaceId, status: data.startDate > new Date().toISOString().slice(0, 10) ? 'upcoming' : 'draft', createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); return Promise.resolve(); }); return reference.id; }
export async function activateAgreement(agreement: Agreement) { await runTransaction(db, async transaction => { const conflicts = await transaction.get(query(collection(db, 'rentalAgreements'), where('workspaceId', '==', agreement.workspaceId), where('unitId', '==', agreement.unitId), where('status', '==', 'active'))); if (!conflicts.empty && !conflicts.docs.every(item => item.id === agreement.id)) throw new Error('This unit already has an active rental agreement.'); const unit = doc(db, 'units', agreement.unitId); const tenant = doc(db, 'tenants', agreement.tenantId); const currentUnit = await transaction.get(unit); if (!currentUnit.exists() || currentUnit.data().status === 'inactive') throw new Error('This unit is not available for occupancy.'); transaction.update(doc(db, 'rentalAgreements', agreement.id), { status: 'active', updatedAt: serverTimestamp() }); transaction.update(unit, { status: 'occupied', activeAgreementId: agreement.id, updatedAt: serverTimestamp() }); transaction.update(tenant, { status: 'active', updatedAt: serverTimestamp() }); }); }
export async function endAgreement(agreement: Agreement, status: 'ended' | 'cancelled') { await runTransaction(db, async transaction => { transaction.update(doc(db, 'rentalAgreements', agreement.id), { status, updatedAt: serverTimestamp() }); const unit = doc(db, 'units', agreement.unitId); const tenant = doc(db, 'tenants', agreement.tenantId); transaction.update(unit, { status: 'vacant', activeAgreementId: null, updatedAt: serverTimestamp() }); const remaining = await transaction.get(query(collection(db, 'rentalAgreements'), where('workspaceId', '==', agreement.workspaceId), where('tenantId', '==', agreement.tenantId), where('status', '==', 'active'))); if (remaining.docs.every(item => item.id === agreement.id)) transaction.update(tenant, { status: 'former', updatedAt: serverTimestamp() }); }); }
export const maskIdentity = (value?: string) => !value ? 'Not added' : value.length < 5 ? '••••' : `${'•'.repeat(Math.max(0, value.length - 4))}${value.slice(-4)}`;
